



server:  port: 9995
spring:
  datasource:
    username: system
    password: java
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /Views/
      suffix: .jsp